const DIVISION_TIME_SECOND_OF_ONEDAY = 60 * 60 * 24;
const DIVISION_TIME_SECOND_OF_NINE_HOUR = 1000 + 60 * 60 * 9;

module.exports = {
  DIVISION_TIME_SECOND_OF_ONEDAY,
  DIVISION_TIME_SECOND_OF_NINE_HOUR,
};
