-- migrate:up
CREATE TABLE Posts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL ,
  content VARCHAR(2000), NULL ,
  content_img VARCHAR(3000) NULL,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP  NULL ON UPDATE CURRENT_TIMESTAMP,
  user_id INT NOT NULL,
  CONSTRAINT Posts_user_id_fkey FOREIGN KEY (Users_id) REFFERENCES Users(id)

)

-- migrate:down

DROP TABLE Posts;