-- migrate:up
CREATE TABLE Users(
  id  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(200) NOT NULL,
  password VARCHAR(200) NOT NULL,
  profile_img VARCHAR(1000) NULL,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP  NULL ON UPDATE CURRENT_TIMESTAMP
);


-- migrate:down
DROP TABLE Users;